version: "2"
run:
  issues-exit-code: 1
linters:
  default: all
  disable:
    - depguard
    - tagalign
    - godox
    - varnamelen
    - wrapcheck
  settings:
    revive:
      severity: warning
    staticcheck:
      checks:
        - all
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
    - golines
  settings:
    gofmt:
      simplify: true
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
