services:
  pvz_service:
    build: .
    container_name: avito_pvz
    ports:
      - "54821:54821"
    environment:
      - CONFIG_PATH=config/config.local.yaml
    depends_on:
      db:
        condition: service_healthy
    networks:
      - internal
  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pvz
    ports:
      - "5432:5432"
    command: postgres
    volumes:
      - ./migrations/pg/init.sql/:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - internal

networks:
  internal:
    name: avito_pvz
