db:
  type: postgres
  port: 5432
  host: db
  user: postgres
  password: postgres
  name: pvz
  sslMode: disable
  poolMaxConn: 20
  poolMaxConnLifetime: 1h30m

grpcServer:
  port: 3000
  timeout: 4s

httpServer:
  address: 0.0.0.0:8080
  timeout: 4s
  idleTimeout: 60s

env: local

jwt:
  secretKey: very-secret-key
  expire: 10h
